### ISSUE TITLE
Previous / next spans don't have CSS labels and their content isn't wrapped in a DOM element

### ISSUE THREAD

**Issue by choldgraf** [sunpy/ablog#194]
### Describe the feature

Here's the structure of the previous/next buttons at the bottom of the page:

```html
<div class="section ablog__prev-next">
  <span>
    <a href="post1.html">
      <i class="fa fa-arrow-circle-left"></i>
      Post one with a long-ish title we can use to compare
    </a>
  </span>
  <span>&nbsp;</span>
  <span>
    <a href="post3.html">
      Post three with a long-ish title we can use to compare
      <i class="fa fa-arrow-circle-right"></i>
    </a>
  </span>
</div>
```

There are a few things that make this hard for other themes to style, some suggestions below.

### Proposed solution

A few things that could make this easier for themes to style:

1. The content within each `<a>` could be wrapped in a `<span>` element so that it can be styled independently of the `<i>` elements.
2. Each `<span>` could have a class saying if it is "prev" or "next". e.g. `<span class="ablog__prev">` and `<span class="ablog__next">`
3. The middle `<span>` could then be removed, and instead the default CSS could set the following to make the left/right :

   ```css
   .ablog__prev-next {
     display: flex;
     justify-content: space-between;
   }

   .ablog__prev-next .ablog__next {
      margin-left: auto;
   }
   ```
